"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.persona_router = void 0;
const express_1 = require("express");
const PersonaPC_1 = require("../controlador/PersonaPC");
exports.persona_router = express_1.Router();
exports.persona_router.get('/persona', PersonaPC_1.getPersona);
exports.persona_router.get('/proveedor', PersonaPC_1.getProveedor);
exports.persona_router.get('/cliente', PersonaPC_1.getCliente);
exports.persona_router.get('/conductor', PersonaPC_1.getConductores);
exports.persona_router.get('/buscar/proveedor', PersonaPC_1.getProveedores);
exports.persona_router.get('/buscar/proveedor/vehiculo', PersonaPC_1.getProveedoresOfVehiculos);
exports.persona_router.get('/buscar/cliente', PersonaPC_1.getClientes);
exports.persona_router.get('/buscar/trabajador', PersonaPC_1.getTrabajadores);
exports.persona_router.get('/persona/:id', PersonaPC_1.getPersonaById);
exports.persona_router.post('/persona', PersonaPC_1.postPersona);
exports.persona_router.put('/persona', PersonaPC_1.updatePersona);
exports.persona_router.delete('/persona/:id', PersonaPC_1.deletePersona);
// persona_router.get('/cliente/:id', getClienteById);
